name: Deploy

on:
  pull_request: # By default, it will run on opened and synchronize PR events
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Node.js as specified in .nvmrc file
      # If .nvmrc only has a major version then it will try to install matching LTS release
      # Otherwise it'll install the exact matching version of node
      - name: install node version from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: build react app
        env:
          # REACT_APP_API_SERVER is the url of camelhr api server
          # The value will be hardcoded in the build output
          REACT_APP_API_SERVER: https://api.camelhr.com
        run: |
          node --version
          npm ci
          npm run build

      - name: deploy to cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'camelhr-ui'
          directory: 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
