name: Lint

on:
  push:
    branches:
      - main
  pull_request: # By default, it will run on opened and synchronize PR events

# Note: GitHub does not pass secrets(for security reasons) to PR workflows created with forked repos
# So do not use any actions that require secrets
# The GITHUB_TOKEN secret is allowed with readonly access for PR workflows created with forked repos

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run lint
        run: |
          node --version
          npm ci
          npm run lint

      - name: verify prettier
        run: |
          npm run prettier:check
